lang_char: 'None'
experiment_name: 'rosetta_hippo_300k_v1'
train_data: 'all_data/hippo_300k_v1'
valid_data: 'all_data/validation'
manualSeed: 1111
workers: 6
batch_size: 12 #32
num_iter: 40000
valInterval: 1000000
saved_model: 'saved_models/rosetta_hippo_300k_v1/iter_30000.pth' #'saved_models\crnn_30k_model\best_norm_ED.pth' #'saved_models\crnn_30k_model\best_accuracy.pth' 
FT: False
optim: False # default is Adadelta
lr: 0.25
beta1: 0.9
rho: 0.95
eps: 0.00000001
grad_clip: 5
#Data processing
select_data: 'color-white-google_ocr_train_images' # this is dataset folder in train_data
batch_ratio: '1-1-1'
total_data_usage_ratio: 1.0
batch_max_length: 100000
imgH: 64
imgW: 600
rgb: False
contrast_adjust: False
sensitive: True
PAD: True
contrast_adjust: 0.0
data_filtering_off: False
# Model Architecture
Transformation: 'None'
FeatureExtraction: 'ResNet'
SequenceModeling: 'None'
Prediction: 'CTC'
num_fiducial: 20
input_channel: 1
output_channel: 256
hidden_size: 256
decode: 'greedy'
new_prediction: False
freeze_FeatureFxtraction: False
freeze_SequenceModeling: False